name: Build & Deploy Godot WebGL

# Fire pipeline on merge to main.
on:
  push:
    branches:
      - main
      - deploy-pipeline

env:
  GODOT_VERSION: 4.1
  EXPORT_NAME: test-project-export
  PROJECT_PATH: godot
  BUCKET: godotkwhitejrcom-origin # The bucket created by Terraform.

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1 # Could not get string interpolation to work :(
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Web" "$EXPORT_DIR/web/index.html"
      - name: Upload static files as GitHub Pages artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: build/web
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: build/web

  deploy-github-pages:
    needs: export-web
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

    # needs: export-web
    # name: Deploy to GitHub Pages
    # runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/download-artifact@v4
    #     name: Download artifacts
    #     with:
    #       name: web
    #       path: build/web
    #   - name: Install rsync 📚
    #     run: |
    #       apt-get update && apt-get install -y rsync
    #   - name: Deploy to GitHub Pages 🚀
    #     uses: JamesIves/github-pages-deploy-action@releases/v4
    #     with:
    #       branch: gh-pages # The branch the action should deploy to.
    #       folder: build/web # The folder the action should deploy.
